### PR TITLE
Add support for topological filters

### PR DESCRIPTION
**Pull request by huard**
This PR allows users to filter WFS requests using spatial filters: Intercepts, Contains, Within, Touches, Disjoint, Overlaps, Equals. 

- Add spatial filters in fes2.py;
- Create gml:Point object;

# Notes

- Only works with WFS 2.0 and POST. 
- The `set_filter` method in GetFeature is weird. It expects a GetFeature xml request, instead of just the Filter node.  I've added a shortcut to allow passing a filter XML object directly. Suggestions welcome. I suggest that when passing `filter` to getfeature, we only pass the filter node, not the getfeature node. 
- I've tested it on our own geoserver instance, but unclear how to test this actually works without a live instance somewhere. 
- The implementation bypasses the FilterRequest class, which seemed to target CSW.
- I used dataclasses, but that's only available from 3.7 onward so added it to dependencies if python < 3.7.

# Related
#128

### CODE REVIEW

**Comment by huard** [comment]
Example usage:
```python
from owslib.wfs import WebFeatureService
from owslib.fes2 import Intersects
from owslib.gml import Point
from owslib.util import element_to_string
import geojson


def test_intersects():
    p = Point(id="qc", srsName="http://www.opengis.net/gml/srs/epsg.xml#4326", pos=[-71, 46])
    f = Intersects(propertyname="the_geom", geometry=p)
    intersects = f.toXML()
    wfs = WebFeatureService("https://pavics.ouranos.ca/geoserver/wfs", version="2.0.0")
    resp = wfs.getfeature(typename="public:canada_admin_boundaries", outputFormat="application/json",
                   propertyname="PRENAME", method="POST", filter=intersects)
    out = geojson.load(resp)
    assert out["totalFeatures"] == 1
    assert out["features"][0]["properties"]["PRENAME"] == "Quebec"
```

**Comment by tomkralidis** [comment]
Thanks @huard.  There are no plans to drop 3.6 anytime soon given it is the default Python version on major OSs (i.e. bionic).

**Comment by huard** [comment]
Ok, will modify the PR.

**Comment by huard** [comment]
As mentioned, at the moment the `<Filter>` tag is built into each topological filter. I think ideally, users should be able to compose filters with AND, OR operations. This would require a smarter composition mechanism.

**Comment by huard** [comment]
@kwilcox @lpinner @jorisvandenbossche Is this what you were looking for in issue #128 ?

**Comment by huard** [comment]
@tomkralidis Ready for review.

**Review by tomkralidis — APPROVED** [review]

**Comment by tomkralidis** [comment]
Thanks @huard !

**Comment by GabrielFerrariR** [comment]
is there any provision for stable implementation of geometry types other than Point?

**Comment by huard** [comment]
Not from my part. This PR was meant to solve a problem I had.

**Pull request merged**
