### PR TITLE
add WCS code example to documentation

### PR DESCRIPTION
**Pull request by misev**
in addition fix execution with python 2.

### CODE REVIEW

**Comment by cehbrecht** [comment]
@misev Thanks for adding the wcs example. We have skipped Python 2.x support starting with release 0.19. Could you please revert the py2/py3 compatibility code?

**Comment by misev** [comment]
I reverted the commit. The documentation should be updated here I guess to list pip3 instead of pip? http://geopython.github.io/OWSLib/#install

**Comment by cehbrecht** [comment]
> The documentation should be updated here I guess to list pip3 instead of pip? http://geopython.github.io/OWSLib/#install

I usually work with Python 3 only in my environment ... so I don't need to distinguish. We could emphasis that it works only with Python 3. @tomkralidis what do you think?

**Comment by cehbrecht** [comment]
@misev thanks :)

**Pull request merged**
