### PR TITLE
Python 3.6 EOL, fixing CI

### PR DESCRIPTION
**Pull request by kalxas**

### CODE REVIEW

**Comment by kalxas** [comment]
This seems to fail in parsing a WFS response 

```
=================================== FAILURES ===================================
____________________ [doctest] wfs_MapServerWFSFeature.txt _____________________
001 
002 Imports
003 
004     >>> from owslib.wfs import WebFeatureService
005     
006 Test the getfeature method
007 
008     >>> wfs = WebFeatureService('http://nsidc.org/cgi-bin/atlas_south?', version='1.0.0')
009     >>> response = wfs.getfeature(typename=['glaciers'], maxfeatures=5)
UNEXPECTED EXCEPTION: ParseError('junk after document element: line 123, column 0')
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/doctest.py", line 1337, in __run
    compileflags, 1), test.globs)
  File "<doctest wfs_MapServerWFSFeature.txt[2]>", line 1, in <module>
  File "/home/runner/work/OWSLib/OWSLib/owslib/feature/wfs100.py", line 300, in getfeature
    headers=self.headers, auth=self.auth)
  File "/home/runner/work/OWSLib/OWSLib/owslib/util.py", line 220, in openURL
    se_tree = etree.fromstring(req.content)
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/xml/etree/ElementTree.py", line 1315, in XML
    parser.feed(text)
  File "<string>", line None
xml.etree.ElementTree.ParseError: junk after document element: line 123, column 0
/home/runner/work/OWSLib/OWSLib/tests/doctests/wfs_MapServerWFSFeature.txt:9: UnexpectedException
```

**Comment by kalxas** [comment]
When added Python 3.10 we got this error:
```
=================================== FAILURES ===================================
___________________________ [doctest] namespaces.txt ___________________________
039     # 'om300' does not exist as a namespace, so the below will return nothing
040     >>> ns.get_namespace('om300')
041 
042     # CSW 3.1.1 doesn't exist, so the below will return nothing
043     >>> ns.get_versioned_namespace('csw','3.1.1')
044 
045 
046 Invalid Usage Tests
047 
048     >>> ns.get_namespace()
Differences (unified diff with -expected +actual):
    @@ -1,3 +1,6 @@
     Traceback (most recent call last):
    -...
    -TypeError: get_namespace() ...
    +  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/doctest.py", line 1350, in __run
    +    exec(compile(example.source, filename, "single",
    +  File "<doctest namespaces.txt[15]>", line 1, in <module>
    +    ns.get_namespace()
    +TypeError: Namespaces.get_namespace() missing 1 required positional argument: 'key'
```

**Comment by tomkralidis** [comment]
The 3.10 issue is rooted in how exceptions are emitted. The following works (and maintains test integrity):

```diff
diff --git a/tests/doctests/namespaces.txt b/tests/doctests/namespaces.txt
index 1c484e3..970328a 100644
--- a/tests/doctests/namespaces.txt
+++ b/tests/doctests/namespaces.txt
@@ -48,7 +48,7 @@ Invalid Usage Tests
     >>> ns.get_namespace()
     Traceback (most recent call last):
     ...
-    TypeError: get_namespace() ...
+    TypeError: ...
 
     >>> ns.get_versioned_namespace()
     Traceback (most recent call last):
```

**Comment by tomkralidis** [comment]
The test in `tests/doctests/wfs_MapServerWFSFeature.txt` is caused by a broken / misconfigured WFS. Given this is out of our control, this can moved to `tests/_broken/doctests` for the time being.

**Pull request merged**
