### PR TITLE
update OAProc process list filtering

### PR DESCRIPTION
**Pull request by tomkralidis**
Ensure that `owslib.ogcapi.processes:Processes.processes() returns a list of only processes (not links).

### CODE REVIEW

**Review by kalxas — APPROVED** [review]

**Review by DIEGOHJ566 — COMMENTED** [review]
@coveralls

**Review by DIEGOHJ566 — COMMENTED** [review]
@coveralls

**Review by DIEGOHJ566 — COMMENTED** [review]
@DIEGOHJ566

**Review by DIEGOHJ566 — COMMENTED** [review]
@DIEGOHJ566

**Pull request merged**
