### PR TITLE
fix #248

### LINKED ISSUE #248: UnicodeEncodeErrors with repr/str
Installed latest OWSlib 0.9.0, and noticed UnicodeEncodeErrors:

```
from owslib.sos import SensorObservationService
sos = SensorObservationService("http://sos.irceline.be/sos")
```

```
In [23]: sos.contents
...
UnicodeEncodeError: 'ascii' codec can't encode characters in position 49-50: ord
inal not in range(128)
```

But not sure this is an error in the code, or a problem in what the sos returns

### PR DESCRIPTION
**Pull request by pesekon2**
unicode encodings in SOS GetCapabilities

### CODE REVIEW

**Comment by kwilcox** [comment]
Did you try to use [this six method](https://pythonhosted.org/six/#six.python_2_unicode_compatible) before reverting to the conditionals?

**Comment by pesekon2** [comment]
I did, but it didn't worked for me. Now I have found why: https://github.com/benjaminp/six/issues/148

It doesn't support __repr__. I think it should be OK to use this reverting and recode it after the __repr__ support. But if you wish, I can try to use six and rewrite somehow the __repr__ method.

**Comment by pesekon2** [comment]
Hi again. So what do you think about it?

**Comment by cehbrecht** [comment]
@pesekon2 
I close the PR in favor of #477. Improvements can be added in follow-up pull-requests.

**Pull request closed without merging**
