### PR TITLE
SOS namespace addition

### PR DESCRIPTION
**Pull request by gamesbook**
Adds the 'sa' namespace for handling SOS data.  An example from a GetObservation request:

```
<om:featureOfInterest xlink:title="my_sensor_id">
    <sa:SamplingPoint gml:id="my_sensor_id">
        <sa:sampledFeature xlink:href="urn:ogc:def:nil:OGC:unknown"/>
        <sa:position>
            <gml:Point gml:id="point_sf_42">
                <gml:pos srsName="urn:ogc:def:crs:EPSG::4326">15.751542 18.280503</gml:pos>
            </gml:Point>
        </sa:position>
    </sa:SamplingPoint>
</om:featureOfInterest>
```

### CODE REVIEW

**Comment by tomkralidis** [comment]
@gamesbook any chance we can add a test or two?

**Comment by gamesbook** [comment]
Hi Tom

I have added a namespace test (but cannot get it to pass locally).  

I am not sure where to add a test for the GetObservation request patch?  If you can point me in the right direction, I will attempt to do so.

Derek

**Comment by tomkralidis** [comment]
Hi Derek: thanks.  FYI I ended up merging this manually as there some merge issues and adding some SOS 2 compatibility.

To add a test case, you can either add a test file like https://github.com/geopython/OWSLib/blob/master/tests/doctests/sos_ngmp.txt or add to an existing test case.  Then feel free to issue another PR.

**Comment by gamesbook** [comment]
Thanks Tom!  Sorry - I have been away for a month.

**Pull request merged**
