### PR TITLE
status set to 'Exception' inside _parseExceptionReport

### PR DESCRIPTION
**Pull request by DrMenny**
There's a bug in the monitorExecution() function:

if the execution.status is not _'None'_ and there's an ExceptionReport, the _monitorExecution()_ will be trapped inside the while loop, because the _parseExceptionReport() cannot set the execution.status to 'Exception'.

In the image you can see that the error is printed every 3 seconds and it gets bigger and bigger because the _parseExceptionReport() appends the error each time the function is called.

image

If the self.status is set as 'Exception' when the _parseExceptionReport() is called, the error is printed just once and the monitorExecution() is stopped.

### CODE REVIEW

**Comment by DrMenny** [comment]
I don't understand what's wrong with the build.

**Comment by DrMenny** [comment]
I just tried to build with the original code (the actual geopython/OWSLib) but the build fails anyway.

`tests/test_wfs3_pygeoapi.py::test_wfs3_pygeoapi FAILED`

Can you please consider my pull request anyway? Thanks (I will push my changes now)

**Comment by DrMenny** [comment]
Here's my last commit. I tested the code and it works. 

image

Thank you for your attention!

**Comment by DrMenny** [comment]
> geopython/owslib#578 add WFS3 api() call with tests and doc #579 
implemented

**Comment by cehbrecht** [comment]
@DrMenny merged. Thanks :)

**Comment by DrMenny** [comment]
> @DrMenny merged. Thanks :)

Thank you :) Are you going to release v0.18 soon?

**Pull request merged**
