### PR TITLE
Code style with autopep8 and initial steps for python 3 support

### PR DESCRIPTION
**Pull request by tbicr**
Look like code have many different code styles at once. I use auto tools as `autopep8` and manual checking for update code. Also it contain steps move to python 3 support.

Patches take care at most about code style and python 3 compatibility and didn't:
- line length, but now it can be too long
- double and single quotes for strings (for code used more single for docstring double)

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
I would be very interested in having a python 3 compatible OWSlib. 
How is it going with this? 
Is there anything I can help with?

**Comment by tomkralidis** [comment]
There has been some smaller PRs in the past months.  I suggest following this path.

**Comment by jorisvandenbossche** [comment]
Ah, yes I see. The merged PRs are #225 and #226

**Comment by tomkralidis** [comment]
@jorisvandenbossche to add, see related thread on owslib-devel: http://lists.osgeo.org/pipermail/owslib-devel/2015-April/000272.html

**Pull request closed without merging**
