### PR TITLE
Add WCS 2.0.0 & 2.0.1 capabilities that match WCS 1.0

### PR DESCRIPTION
**Pull request by doclements**
This patch add the same abilities that exist for WebCoverageService verison 1 for version 2.0.0 and 2.0.1 versions.  This is my first contribution to a large opensource project and i am also not a computer scientist. Any guidance if this pull request isnt correct would be greatly appreciated.

### CODE REVIEW

**Comment by StephanSiemen** [comment]
Hi @doclements,
very important functionality for us. Used the fork successfully. When could we see this in the main version?
Thanks
Stephan

**Comment by doclements** [comment]
i will redo the tests to match the new style

**Comment by cehbrecht** [comment]
@doclements 
the doctest `wcs_200.txt` is failing. Is this due to your PR? When you convert your tests to "normal" tests maybe you can take care of it as well :)

**Comment by doclements** [comment]
Tests have been added in the new pythonic style. Original doctest has been fixed to pass also.

**Comment by cehbrecht** [comment]
Changes look reasonable to me.

I will make a squash-merge (1 commit) for the patch.

We discussed at the coding-sprint in Bonn to have a ticket for each PR. The ticket can be closed automatically by merging a PR. A PR should not have to many commits:
http://pywps.readthedocs.io/en/master/development.html 

I haved added a ticket for the PR now, just for completeness:

This PR fixes #430.

**Comment by cehbrecht** [comment]
@doclements 
merged. Thanks for contribution :)

**Comment by doclements** [comment]
@cehbrecht awesome, thanks for helping me through the process :-)

**Pull request merged**
