### PR TITLE
add WMS 1.3.0 support

### PR DESCRIPTION
**Pull request by roomthily**
(same changelog)

For #25 and includes the patch in the PR for #312 and BOM handling from #256. All of the mods to wms.py should be in 1.1.1 and 1.3.0.

WMS:

- convert to the factory structure
- updated handling for dimensions (this I haven't found a live service for, fyi)
- expanded doctests for 1.3.0 and GetMap requests

util.py:

- update openURL exception handling to include the vnd_* errors
- update openURL exception handling for the additional namespaces
- added strip_bom for the BOM patch

The change to the sos test is for the Exception class. That may be a breaking change for you? 

I am getting connection errors in the tests for service calls in wcs_idee.txt and wmts_SFSWorldWMTSCapabilities.txt:

```
HTTPError: 404 Client Error: No Encontrado for url: http://www.idee.es/wcs/IDEE-WCS-UTM30N/wcsServlet?service=WCS&request=GetCapabilities

ConnectTimeout: HTTPConnectionPool(host='server.caris.com', port=80): Max retries exceeded with url: /spatialfusionserver/services/ows/wmts/World?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=World&STYLE=default&TILEMATRIXSET=GlobalCRS84Scale&TILEMATRIX=0&TILEROW=0&TILECOL=0&FORMAT=image%2Fpng (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x108088390>, 'Connection to server.caris.com timed out. (connect timeout=30)'))
```

Cheers.

### CODE REVIEW

**Comment by tomkralidis** [comment]
@roomthily there are merge conflicts, can you check please?

**Comment by sbrunner** [comment]
Isn't the file `tests/resources/wms_nccs_nasa_getcap_130.xml` to big?

**Comment by tomkralidis** [comment]
@roomthily any chance you can take a look at the merge conflicts?

**Comment by tomkralidis** [comment]
Applied clean with #343. Thanks @roomthily!

**Pull request closed without merging**
