### PR TITLE
fix CRS for non-int code by URL

### PR DESCRIPTION
**Pull request by fmigneault**
Follow up on #897 with the generated URL assuming EPSG

### CODE REVIEW

**Comment by fmigneault** [comment]
@tomkralidis 
Thanks for merging #897 quickly. Is it possible to include this one as well?
Also, is it possible to have a new release to resolve these issues as well as all other patches since https://github.com/geopython/OWSLib/releases/tag/0.29.2?

**Comment by tomkralidis** [comment]
@fmigneault please ping me next week and I'll make a release as part of the [OSGeo Community Sprint](https://wiki.osgeo.org/wiki/OSGeo_Community_Sprint_2023).

**Comment by fmigneault** [comment]
Hi @tomkralidis. Let me know when you get around to this. Thanks again!

**Comment by tomkralidis** [comment]
0.29.3 released: https://github.com/geopython/OWSLib/releases/tag/0.29.3

**Pull request merged**
