### PR TITLE
Adding Python 3.10 in CI

### PR DESCRIPTION
**Pull request by kalxas**

### CODE REVIEW

**Comment by kalxas** [comment]
```
=================================== FAILURES ===================================
___________________________ [doctest] namespaces.txt ___________________________
039     # 'om300' does not exist as a namespace, so the below will return nothing
040     >>> ns.get_namespace('om300')
041 
042     # CSW 3.1.1 doesn't exist, so the below will return nothing
043     >>> ns.get_versioned_namespace('csw','3.1.1')
044 
045 
046 Invalid Usage Tests
047 
048     >>> ns.get_namespace()
Differences (unified diff with -expected +actual):
    @@ -1,3 +1,6 @@
     Traceback (most recent call last):
    -...
    -TypeError: get_namespace() ...
    +  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/doctest.py", line 1350, in __run
    +    exec(compile(example.source, filename, "single",
    +  File "<doctest namespaces.txt[15]>", line 1, in <module>
    +    ns.get_namespace()
    +TypeError: Namespaces.get_namespace() missing 1 required positional argument: 'key'
```

**Comment by kalxas** [comment]
See https://github.com/geopython/OWSLib/pull/850#issuecomment-1345164716

**Comment by kalxas** [comment]
Still:
```
=================================== FAILURES ===================================
___________________________ [doctest] namespaces.txt ___________________________
044 
045 
046 Invalid Usage Tests
047 
048     >>> ns.get_namespace()
049     Traceback (most recent call last):
050     ...
051     TypeError: ...
052 
053     >>> ns.get_versioned_namespace()
Differences (unified diff with -expected +actual):
    @@ -1,3 +1,6 @@
     Traceback (most recent call last):
    -...
    -TypeError: get_versioned_namespace() ...
    +  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/doctest.py", line 1350, in __run
    +    exec(compile(example.source, filename, "single",
    +  File "<doctest namespaces.txt[16]>", line 1, in <module>
    +    ns.get_versioned_namespace()
    +TypeError: Namespaces.get_versioned_namespace() missing 1 required positional argument: 'key'
```

**Comment by tomkralidis** [comment]
Closed in lieu of #891

**Pull request closed without merging**
