### PR TITLE
Fix reading style in getCap

### PR DESCRIPTION
**Pull request by mlefort**
When a style is found without "title" or "name", a ValueError is raised 

However, the style should only be ignored, otherwise it's too restrictive for some services
(ex : https://inspire.cadastre.gouv.fr/scpc/31555.wms?service=WMS&request=GetCapabilities)

### CODE REVIEW

**Comment by cehbrecht** [comment]
@mlefort I can not say if this is a valid approach. Maybe some else familiar with WMS can comment? 

The tests are failing due to pep8 check:
```
$ flake8 owslib

owslib/map/wms130.py:585:17: E265 block comment should start with '# '
```

**Comment by mlefort** [comment]
Thank you for your answer. I corrected the error linked to pep8 check. 
However, there seems to be always a problem with the tests on python 3.6, but I don't see the connection with my modification.

**Comment by tomkralidis** [comment]
Note that `Name` and `Style` are required elements as per WMS 1.3.0.

**Comment by mlefort** [comment]
You're right but that's not the point : if a style is incorrect, it should simply be ignored without generating an error. That's what other WMS clients do, such as QGIS. The lib should be able to handle WMS that is not perfect.

**Pull request closed without merging**
