### PR TITLE
Added support of setting output in ResponseDocument mimetype

### PR DESCRIPTION
**Pull request by eran-pinhas**
solving issue #539

### CODE REVIEW

**Comment by cehbrecht** [comment]
@huard are you ok with this PR?

**Comment by cehbrecht** [comment]
@eran-pinhas Please check the spelling changes. I can merge it then.

**Comment by eran-pinhas** [comment]
oops 🤦‍♂️

fixing

**Comment by cehbrecht** [comment]
@eran-pinhas thanks :)

**Pull request merged**
