### PR TITLE
Update pyproj syntax and fix some issue in WFS

### PR DESCRIPTION
**Pull request by cheginit**
This PR includes the following improvements/fixes:
1. Update `pyproj` syntax for the transform operation according to the proposed style on their [website](https://pyproj4.github.io/pyproj/stable/gotchas.html) to fix the deprecation warning.
2. Fix an issue in `WFS` where a list addition operation was not assigned to the intended variable.
3. Remove the unnecessary `else` in an if-block, since an exception is being raised.

### CODE REVIEW

**Review by huard — APPROVED** [review]
Could you add a test that covers the bug this fixes to avoid future regression?

**Comment by cheginit** [comment]
Sure, I'll work on it.

**Comment by cheginit** [comment]
I am having difficulty finding a WFS service with `Operations` for `FeatureType`s themselves not just the parent `FeatureTypeList`. I tried a couple of services but their `elem.findall(nspath("Operations/*")` are empty. Do you know such WFS service?

**Comment by cheginit** [comment]
Sure. Will do that.

**Comment by cheginit** [comment]
Is there anything else that you would like to include in this PR?

**Comment by huard** [comment]
Ideally all tests would pass before merging, but I assume the failure I see is unrelated to your PR?

@tomkralidis Any idea?

**Comment by tomkralidis** [comment]
+1 to merge this PR given the test failures are unrelated.  If the unrelated test failures persist we should address as part of another fix to the tests.

**Comment by cheginit** [comment]
Yes, it seems that the tests that are failing require another PR. I confirmed that the tests that I added for this PR pass without any issue.

**Comment by cheginit** [comment]
@huard I am wondering what's your plan for this PR?

**Pull request merged**
