### PR TITLE
Fixing WMTS parameter resolution

### PR DESCRIPTION
**Pull request by dvbmgr**

### CODE REVIEW

**Comment by dvbmgr** [comment]
hi, any plans on taking a look at this PR ? thanks !:)

**Review by huard — APPROVED** [review]

**Comment by huard** [comment]
@chrisgraf Could you take a look at this PR?

**Comment by chrisgraf** [comment]
@huard yes, this looks cleaner/better

**Review by chrisgraf — APPROVED** [review]

**Review by chrisgraf — APPROVED** [review]

**Comment by huard** [comment]
Thanks !

**Pull request merged**
