### PR TITLE
Wms130 addition

### PR DESCRIPTION
**Pull request by roomthily**
For #25 - WMS 1.3.0 integration.

The tests are for 1.3.0 version of the existing Mesonet test, the National Atlas 1 million scale service and an AZGS ArcGIS Server-based service. 

Changes:
- new crs_list to both 1.3.0 and 1.1.1 handling to capture all defined BoundingBox elements. The original boundingBox parameter is unaffected.
- addition of a featureListUrls parameter for the ContentMetadata (1.3.0).
- axis order handling (GetMap) for EPSG:4326, EPSG:4269 and EPSG:4267 (note: I haven't located a good list of affected EPSG codes affected and filters in existing code bases are either EPSG:4326 only or are overly broad. Aiming for pareto complete.)
- moved 1.1.1 and 1.3.0 code to match the WxS patterns with the default version at 1.1.1 for backwards compatibility. 
- updated Extents handling to the Dimension structure in 1.3.0.

That should cover the major updates. Let me know if there's anything wonky or missing or anything like that.

Cheers.

### CODE REVIEW

**Comment by tomkralidis** [comment]
Thanks @roomthily .  Initial comments (I'll have have more time tomorrow):

Please see build errors at: https://travis-ci.org/geopython/OWSLib/builds/54595442 . AFAICT:
* decimal precision requires some investigation (https://travis-ci.org/geopython/OWSLib/jobs/54595443#L490)
* we don't rely on `lxml.eteee` (don't use `elem.xpath()`) https://travis-ci.org/geopython/OWSLib/jobs/54595446#L494
* looks like some syntax errors in the tests: https://travis-ci.org/geopython/OWSLib/jobs/54595443#L450
* there are some unrelated test failures not related to WMS, we can ignore for this PR
* NameError in https://travis-ci.org/geopython/OWSLib/jobs/54595443#L419
* not sure if it helps or not, but we do some rudimentary CRS/axis order handling in https://github.com/geopython/OWSLib/blob/master/owslib/crs.py

**Comment by roomthily** [comment]
Ah, well we may be at a bit of an impasse then. Let me doublecheck on
internal priorities for my time on this work for moving ahead from my end.

Without a git blame related, CSW fails are not going to fall in my scope of
work :).

Cheers,
Soren

**Comment by tomkralidis** [comment]
@roomthily to clarify, you can ignore non-WMS 1.3 related failing tests.

**Comment by jachym** [comment]
Hi,

the list of "inverse" EPSG codes I always took from mapserver

see for example:

http://redmine.ccss.cz/projects/hslayers/repository/entry/trunk/source/patches/Layer/WMS.js

at least 3035 should be there to (used for INSPIRE, but HAS axis "inverted")

**Comment by kwilcox** [comment]
@roomthily I'd really like to get this included in OWSLib.  Is there any way you can rebase on the current master (py3 compat) while taking into account the comments from @tomkralidis?

**Comment by roomthily** [comment]
Let me sort out some scheduling with my supervisor. I have no issues with
rebasing, etc, it's just a timing problem :). Do you have a particular time
frame?

**Comment by roomthily** [comment]
Well.

So the WMS 1.3.0 was just a part of some changes we made for
GetCapabilities harmonization, some WCS issues, and support for less than
valid service responses (we have a project need to support as many dialects
and implementations of the things as we can, valid or not, horribly nested
or not). Which puts our branch well out-of-sync and maybe with features not
of interest to OWSlib proper. I would also note that I haven't had a chance
to look through your last few commits to know the extent of the divergence.

I don't know if anyone is around right now for the OGC meeting in Boulder
(I could pop back by for a chat, it might be faster?) or if we should set
up a telecon time? We are certainly all for community and would like to
contribute some/any modifications back.

Let me know and I will, at a minimum, try to get a better changelog running
on our fork for reference.

Cheers,
roomthily

**Comment by aabhayas** [comment]
Hi Roomthily,

I downloaded the git pull request (https://github.com/geopython/OWSLib/pull/223) to do some quick testing on some of our WMS 1.3.0 services. I found two issues with the current code base.

WMS 1.3.0 Call will fail if time dimension is not present

                Wms130.py line 494
                                time_dimension = next(iter(elem.xpath(time_xpath)), None)

WMS 1.3.0 Call will fail if elevation is not present

Wms130.py line 502
                elev_dimension = next(iter(elem.xpath(elev_xpath)), None)

Regards
Anuruddha Abhayasinghe
[Description: Description: Description: Description: http://web.bom.gov.au/eiab/publishing/images/bureau_logo.gif]
Geospatial Data and Access
Data Integration and Access Section
Environmental Information Branch
Bureau of Meteorology
GPO Box 1289 Melbourne VIC 3001
Level 6, 700 Collins Street, Docklands VIC 3008
Tel: +61 3 9669 4589 | aabhayas@bom.gov.au<mailto:aabhayas@bom.gov.au>
www.bom.gov.au<http://www.bom.gov.au/>

**Comment by roomthily** [comment]
Not a surprise :). So those two issues fall under the preferred no xpath
constraint anyway.

I need to look through the list again so no promises.

Cheers,
roomthily

**Pull request closed without merging**
