### PR TITLE
Fix lxml import for ParseError, fix csw test

### PR DESCRIPTION
**Pull request by daf**
As pointed out by @drnextgis on 66200494ab59, I had the import for ParseError in the lxml path incorrect.  This patch fixes it, as well as an unrelated CSW test that had started failing because the source happened to be producing less records than when the test was written (moving targets and all).

### CODE REVIEW

**Comment by daf** [comment]
@tomkralidis the test failures on travis are only a timeout, same error on each one.

**Comment by tomkralidis** [comment]
@daf what about this error? https://travis-ci.org/geopython/OWSLib/jobs/69449926#L386

**Comment by daf** [comment]
Oh sure, make my spot checking look bad :)  I'll check it out..

**Comment by daf** [comment]
And now a lesson in why you always check the easiest/most obvious thing first: NODC geoportal is returning 503s on every request. (this was after I had built a docker container for OWSLib to run python 3.2 as that was the easiest way to get that version going)

The error could likely be better (check HTTP code somewhere instead of trying to parse an error page) but that's a separate issue and not affected by this PR.

**Comment by drnextgis** [comment]
@tomkralidis what reason this PR is still unmerged?

**Comment by drnextgis** [comment]
Thanks!

**Pull request merged**
