### PR TITLE
Support for WMS 1.3.0

### PR DESCRIPTION
**Pull request by roomthily**
For #25 and includes the patch in the PR for #312 and BOM handling from #256. All of the mods to wms.py should be in 1.1.1 and 1.3.0.

Changelog

WMS:

- convert to the factory structure
- updated handling for dimensions (this I haven't found a live service for, fyi)
- expanded doctests for 1.3.0 and GetMap requests

util.py:

- update openURL exception handling to include the vnd_* errors
- update openURL exception handling for the additional namespaces
- added strip_bom for the BOM patch

### CODE REVIEW

**Comment by jachym** [comment]
congrats, I've started similar work some time back, but you managed to get it together.

Question to all: does it make sense, before pull request is merged, to merge all commits into single commit? It's probably more easy for review. (git rebase -i COMMIT_HASH^)

**Comment by tomkralidis** [comment]
@jachym +1.  @roomthily you can also do `git rebase -i HEAD~33` (this PR has 33 commits).

**Comment by roomthily** [comment]
Will try to get to it in the next day or two.

On Mon, Apr 25, 2016 at 4:27 AM, Tom Kralidis <notifications@github.com>
wrote:

> @jachym <https://github.com/jachym> +1. @roomthily
> <https://github.com/roomthily> you can also do git rebase -i HEAD~33
> (this PR has 33 commits).
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/geopython/OWSLib/pull/323#issuecomment-214252135>
>



-- 

Soren Scott
Research Coder
The Ronin Institute for Independent Scholarship
soren.scott@ronininstitute.org

just a head's up - taking a bit of a sabbatical so if i don't
get back to you right away, no worries.

**Comment by tomkralidis** [comment]
FYI I've looked into this deeper and it appears that the commits in this PR are over a long period of time, where commits happened in between.  It might be a bit messy to try and squash this using `git rebase`.

Having said this, I would suggest a clean branch based on current master with the WMS 1.3.0 based changes cleanly applied (some manual work probably needed).

@roomthily I'm willing to do this and will attribute the (much requested and awesome!) enhancement to you in the PR, but I want to make sure 1./ this is okay with you and 2./ you haven't begun this already

**Comment by tomkralidis** [comment]
@roomthily any objections to my previous [comment/question](https://github.com/geopython/OWSLib/pull/323#issuecomment-219096672)?

**Comment by tomkralidis** [comment]
@roomthily bump.  Any objections/comments?

**Comment by roomthily** [comment]
No, no all fine, was in agreement on the age of the commits and some funky history rewriting in rebase. Very clean PR fork in a few minutes.

**Pull request closed without merging**
