### PR TITLE
added some tests for services without filters or boundingboxes (issue #675)

### PR DESCRIPTION
**Pull request by klix2**
added some tests to avoid crash from issue #675
allowing services who dont provide filters or boundingboxes
 ex : https://data.strasbourg.eu/api/wfs

### CODE REVIEW

**Comment by cehbrecht** [comment]
@tomkralidis ok to merge?

**Comment by klix2** [comment]
found one more issue with data.strasbourg.eu... there are some datasets
listed with no schema.
these are clearly bad datasets but OSWlib should not crash
so i added one more test to the _construct_schema function
so this datasets are nicely ignored.

**Comment by tomkralidis** [comment]
+1

**Comment by cehbrecht** [comment]
@klix2 Could you please fix pep8? Tests are failing:
```
$ flake8 owslib
```

**Comment by klix2** [comment]
fixed

**Comment by cehbrecht** [comment]
@klix2 thanks :) merged.

**Pull request merged**
