### PR TITLE
Add json responses from the 52N OGCAPI test server implementation

### PR DESCRIPTION
**Pull request by huard**
Could be used for static testing.

### CODE REVIEW

**Comment by cehbrecht** [comment]
@huard adding a readme with the requests (urls)? you can merge it to:
https://github.com/geopython/OWSLib/tree/feature-749-ogcapi-processes

**Comment by huard** [comment]
Done, but git doesn't allow me to push.

**Comment by cehbrecht** [comment]
> Done, but git doesn't allow me to push.

you mean you can not merge? I think should have rights ... you can change the base branch from master to `feature-749-ogcapi-processes`

**Comment by fmigneault** [comment]
The first step of `API` in https://github.com/geopython/OWSLib/blob/master/owslib/ogcapi is to fetch the JSON or YAML schema of the remote API. So I think evaluated instances should use the response they return for validation. 

For static analysis, maybe we should target the official https://github.com/opengeospatial/ogcapi-processes/ schemas ?

**Comment by huard** [comment]
@cehbrecht I can't push to your branch... 

@fmigneault I'm not sure I know how we would test the client against the schemas. What do you have in mind ?

**Review by cehbrecht — APPROVED** [review]

**Comment by cehbrecht** [comment]
@huard merged. Can also use issue #749 for discussion.

**Comment by fmigneault** [comment]
@huard 
I just mean that instead of using static files posted to this repo which can become out of sync, we should use the ogc-api references directly. 
Static testing of any endpoint could then be evaluated against against those schemas to detect where API responses do not respect the reference OpenAPI. 
That would allow owslib users to run conformance tests against official schemas, which is something notably lacking for WPS.

**Comment by fmigneault** [comment]
@huard 
Using something similar to https://pypi.org/project/openapi-schema-validator/
Compare the received JSON response with expected OGC-API schemas.

**Pull request merged**
