### PR TITLE
Data models for OGC API Processes

### PR DESCRIPTION
**Pull request by huard**
pydantic data models for the different objects transacted by the API.

### CODE REVIEW

**Review by cehbrecht — APPROVED** [review]

**Comment by cehbrecht** [comment]
Tests are failing due to missing pydantic:
```
ModuleNotFoundError: No module named 'pydantic'
```

**Comment by cehbrecht** [comment]
@huard @tomkralidis we probably want a seperation of these models? 

* core
  * collections
    * records
    * features
  * processes

**Comment by cehbrecht** [comment]
Looks good :smile: I can update the `ogcapi.processes` to use this model.

**Comment by huard** [comment]
Are models shared across collections, features, processes ? If not that separation sounds logical.

**Comment by cehbrecht** [comment]
Looks `ForwardRef` is not support on py36 ... can we remove it? 
```
___________________ ERROR collecting owslib/ogcapi/models.py ___________________
Traceback (most recent call last):
  File "/home/runner/work/OWSLib/OWSLib/owslib/ogcapi/models.py", line 2, in <module>
    from typing import Any, List, Union, Optional, Dict, ForwardRef
ImportError: cannot import name 'ForwardRef'
```

**Comment by huard** [comment]
Yes, we can remove it for now.

**Comment by fmigneault** [comment]
@huard @cehbrecht `List["myref"]` is equivalent to `List[ForwardRef["myref"]]`
`ForwardRef` is for internal use

**Pull request merged**
