### PR TITLE
Revert to previous pyproj version

### PR DESCRIPTION
**Pull request by kalxas**

### CODE REVIEW

**Comment by kalxas** [comment]
This now only has 3 fails due to remote WFS service error

**Comment by tomkralidis** [comment]
CI failures unrelated.

**Comment by musicinmybrain** [comment]
Is there an issue tracking the problems you’re having with pyproj 3.3, or a known path toward resolving them? Thanks!

**Comment by sbrunner** [comment]
Why this limitation?

**Comment by fmigneault** [comment]
@tomkralidis 
Would it be possible to have a `0.26.1` fix with the reverted requirement in https://github.com/geopython/OWSLib/commit/a6105226f1c8466c3b1e9998747d0dbf01434129 before all the *OGC API - Processes* items are added?

**Comment by tomkralidis** [comment]
@fmigneault we should be able to cut a release during the FOSS4G code sprint.  Is there forthcoming work coming for OGC API - Processes?

**Comment by fmigneault** [comment]
I don't know if there will be significant work about *OGC API - Processes*, but I think a patch release should be done beforehand such that `pyproj` can work once again on Python 3.10 without possibility introducing new issues from new features.

**Pull request merged**
