### PR TITLE
Feature/wcs headers integration

### PR DESCRIPTION
**Pull request by ferreteleco**
Updated PR with no changes in formatting and more verbosity in commit messages

### CODE REVIEW

**Comment by cehbrecht** [comment]
Please fix pep8:
```
flake8 owslib 
owslib/wcs.py:21:88: E231 missing whitespace after ','
owslib/wcs.py:42:80: E231 missing whitespace after ','
owslib/wcs.py:45:74: E231 missing whitespace after ','
owslib/wcs.py:48:74: E231 missing whitespace after ','
owslib/wcs.py:51:74: E231 missing whitespace after ','
owslib/wcs.py:54:74: E231 missing whitespace after ','
owslib/coverage/wcsBase.py:71:61: E231 missing whitespace after ','
```

**Review by cehbrecht — APPROVED** [review]

**Comment by cehbrecht** [comment]
tests are passing with latest fix on master.

**Comment by cdaller** [comment]
This merge breaks the code:

Example
```
#!/usr/bin/python3

from owslib.sos import SensorObservationService

service = SensorObservationService('http://sensorweb.demo.52north.org/52n-sos-webapp/sos/kvp', version='2.0.0')

offering = 'ws2500'
observedProperty = 'AirTemperature'

get_obs = service.get_operation_by_name('GetObservation')
response = service.get_observation(responseFormat='http://www.opengis.net/om/2.0', offerings=[offering],
                                   observedProperties=[observedProperty])
```

Results in 
```python3
Traceback (most recent call last):
  File "/Users/xxxx/testrequest.py", line 11, in <module>
    response = service.get_observation(responseFormat='http://www.opengis.net/om/2.0', offerings=[offering],
  File "/Library/Python/3.8/site-packages/owslib/swe/observation/sos200.py", line 205, in get_observation
    response = openURL(base_url, request, method,
  File "/Library/Python/3.8/site-packages/owslib/util.py", line 200, in openURL
    rkwargs['params'] = unquote(data) if data else None
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/parse.py", line 635, in unquote
    string.split
AttributeError: 'dict' object has no attribute 'split'
```

The problem is that the unquote call in utils.py line 200 throws an exception if the data argument is a dict. Which is the case in the get_observation call.

**Comment by jsanchezfr** [comment]
Still open... 
I had to remove the "unquote" to make it work with SOS.

**Pull request merged**
