### PR TITLE
[WIP] handle non-XML responses

### PR DESCRIPTION
**Pull request by tomkralidis**

### CODE REVIEW

**Comment by cehbrecht** [comment]
This PR fixes #493.

**Comment by cehbrecht** [comment]
@tomkralidis I have tried with the test mentioned in #493. Python 2.7 might work (didn't check) but Python 3.x does not. The response is in bytes (not string):
`response = b'{"csw:GetRecordByIdResponse": "..."}'`

So, we need some decode method handling python 2.x and python 3.x (`util.decode_sring()`). For Python 3.6 this converts bytes to string:
```
response.decode('utf-8')
'{"csw:GetRecordByIdResponse": "1"}'
```

OR

we may use a json loads test ... or relying on the mime type?
```
try:
    json.loads(response)
    is_json = True
except Exception
    is_json= False
```

We could add the mention test in #493 to the test suite.

**Comment by cehbrecht** [comment]
@tomkralidis do you have an update on this PR? Though the status of owslib is not perfect do we want to got for a release 0.17?

**Comment by tomkralidis** [comment]
@cehbrecht I haven't had a chance to follow up on this.  Pushing to 0.18.

**Pull request closed without merging**
